/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as AdminVerifyEmailRouteImport } from './routes/admin/verify-email'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AdminForgotPasswordSentRouteImport } from './routes/admin/forgot-password_.sent'
import { Route as AdminAdminUsersUserIdRouteImport } from './routes/_admin/admin.users_.$userId'
import { Route as AdminAdminUsersCreateRouteImport } from './routes/_admin/admin.users_.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifyEmailRoute = AdminVerifyEmailRouteImport.update({
  id: '/admin/verify-email',
  path: '/admin/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminForgotPasswordSentRoute = AdminForgotPasswordSentRouteImport.update({
  id: '/admin/forgot-password_/sent',
  path: '/admin/forgot-password/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminUsersUserIdRoute = AdminAdminUsersUserIdRouteImport.update({
  id: '/admin/users_/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminUsersCreateRoute = AdminAdminUsersCreateRouteImport.update({
  id: '/admin/users_/create',
  path: '/admin/users/create',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/verify-email': typeof AdminVerifyEmailRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/forgot-password/sent': typeof AdminForgotPasswordSentRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/admin/users/create': typeof AdminAdminUsersCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/verify-email': typeof AdminVerifyEmailRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/forgot-password/sent': typeof AdminForgotPasswordSentRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
  '/admin/users/create': typeof AdminAdminUsersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/verify-email': typeof AdminVerifyEmailRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/admin/forgot-password_/sent': typeof AdminForgotPasswordSentRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/users_/$userId': typeof AdminAdminUsersUserIdRoute
  '/_admin/admin/users_/create': typeof AdminAdminUsersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/setup'
    | '/admin/verify-email'
    | '/admin/users'
    | '/admin/forgot-password/sent'
    | '/admin/'
    | '/admin/users/$userId'
    | '/admin/users/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/setup'
    | '/admin/verify-email'
    | '/admin/users'
    | '/admin/forgot-password/sent'
    | '/admin'
    | '/admin/users/$userId'
    | '/admin/users/create'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/setup'
    | '/admin/verify-email'
    | '/_admin/admin/users'
    | '/admin/forgot-password_/sent'
    | '/_admin/admin/'
    | '/_admin/admin/users_/$userId'
    | '/_admin/admin/users_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminVerifyEmailRoute: typeof AdminVerifyEmailRoute
  AdminForgotPasswordSentRoute: typeof AdminForgotPasswordSentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verify-email': {
      id: '/admin/verify-email'
      path: '/admin/verify-email'
      fullPath: '/admin/verify-email'
      preLoaderRoute: typeof AdminVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forgot-password_/sent': {
      id: '/admin/forgot-password_/sent'
      path: '/admin/forgot-password/sent'
      fullPath: '/admin/forgot-password/sent'
      preLoaderRoute: typeof AdminForgotPasswordSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/users_/$userId': {
      id: '/_admin/admin/users_/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminAdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/users_/create': {
      id: '/_admin/admin/users_/create'
      path: '/admin/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AdminAdminUsersCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminUsersUserIdRoute: typeof AdminAdminUsersUserIdRoute
  AdminAdminUsersCreateRoute: typeof AdminAdminUsersCreateRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminUsersUserIdRoute: AdminAdminUsersUserIdRoute,
  AdminAdminUsersCreateRoute: AdminAdminUsersCreateRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminVerifyEmailRoute: AdminVerifyEmailRoute,
  AdminForgotPasswordSentRoute: AdminForgotPasswordSentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
